FROM alpine:latest

ENV DB_NAME=wordpress
ENV DB_USER=mysql
ENV DB_PASS=pass
ENV DB_HOST=mysql
#to run sql
COPY mysql_test/sql_test.sh .
COPY mysql_test/my.cnf /tmp/my.cnf
VOLUME /var/lib/mysql 
EXPOSE 3306
RUN chmod +x sql_test.sh
RUN apk add gettext
RUN envsubst '${DB_NAME} ${DB_USER} ${DB_PASS} ${DB_HOST}' < sql_test.sh > mysql_test.sh
RUN cat mysql_test.sh
RUN chmod +x mysql_test.sh
CMD /bin/sh

RUN ./mysql_test.sh

RUN apk update && \
    apk add php7 php7-fpm php7-opcache php7-gd php7-mysqli php7-zlib php7-curl php7-mbstring php7-json php7-session php7-zip && \
    mkdir -p /www/tmp && \
	apk add wget curl nginx gettext

RUN mkdir -p /run/nginx

RUN wget https://files.phpmyadmin.net/phpMyAdmin/5.0.1/phpMyAdmin-5.0.1-english.tar.gz && \
	tar -xzvf phpMyAdmin-5.0.1-english.tar.gz --strip-components=1 -C /www && \
	chmod 777 /www/tmp

RUN adduser -D -g 'www' www

COPY config.inc.php .
RUN envsubst '${PORT} ${DB_NAME} ${DB_USER} ${DB_PASS} ${DB_HOST}' < config.inc.php > /www/config.inc.php
COPY nginx.conf /etc/nginx/nginx.conf
COPY nginx.conf /etc/nginx.conf

# Make sure that our ssh daemon keeps restarting

COPY setup.sh .
RUN chmod +x setup.sh

RUN chown -R www:www /var/lib/nginx
RUN chown -R www:www /www
EXPOSE 5000

CMD [ "/bin/sh" ]
