apiVersion: v1
kind: Service
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin-deployment
spec:
  type: LoadBalancer
  selector:
    app: phpmyadmin-deployment
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin-deployment
  template:
    metadata:
      labels:
        app: phpmyadmin-deployment
    spec:
      containers:
      - name: phpmyadmin
        image: phpmyadmin
        imagePullPolicy: Never
        ports:
        - containerPort: 5000
        livenessProbe:
          httpGet:
            path: /
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 60
          periodSeconds: 20
          timeoutSeconds: 10
        volumeMounts:
        - name: phpmyadmin-persistent-storage
          mountPath: /var/www/localhost/htdocs
      volumes:
      - name: phpmyadmin-persistent-storage
        persistentVolumeClaim:
          claimName: phpmyadmin-pv-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: phpmyadmin-pv-claim
  labels:
    app: phpmyadmin-deployment
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
