apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment-test
  labels:
    app: wordpress-deployment-test
spec:
  selector:
    matchLabels:
      app: wordpress-deployment-test
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-deployment-test
    spec:
      containers:
      - name: wordpress
        image: wordpress
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5050
        volumeMounts:
        - name: wordpress-persistent-storage
          mountPath: /www
      volumes:
      - name: wordpress-persistent-storage
        persistentVolumeClaim:
          claimName: wordpress-pv-claim
